# 主题仍在测试阶段，正在进一步完善，请在使用前先确认主题是否符合您的需求。
# v0.1

# Hero 
turbo-hero:
  title: 每个宇宙都拥有无限可能 # 标题
  description: 我们正在创造一个个全新的富有创意的小说宇宙，每一位角色都有无限的可能性，在这个时代的浪潮中，我们将为你带来最具创新性的小说宇宙 # 描述

# Navigation
navigation:
  float-nav: # Floating Navigation For Index
    - name: 项目
      href: '#projects'
    - name: 产品
      href: '#products'
    - name: 专辑
      href: '#albums'
    - name: 短片
      href: '#short-videos'
    - name: 团队
      href: '#team-members'
  main-nav:
    - name: 政策
      href: '/policy'
    - name: 设计
      href: '/design'
    - name: 文章
      href: '/posts'
    - name: 联系
      href: '/contact'
    - name: 加入我们
      href: '/join_us'

# Project Card
project-card: 
  - title: 无界宇宙
    show-title: false
    image: https://static.turboflint.cn/images/upload/noline-universe-banner.png
    description: 一个专注于青春、艺术和文化的小说宇宙。在这个宇宙中，无论是谁，他们虽然有自己的故事，但又能互相相连起来。
    url: https://noline.turboflint.cn
    status: 已推出
  - title: Find Me
    show-title: true
    image: https://static.turboflint.cn/image/FindMe_Cover.png_compress
    description: xxx
    url: https://find-me.turboflint.cn
# Products
# products: 
#   - title: 燃愿
#     image: https://images.unsplash.com/photo-1745613998978-fae3bf6308fa?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
#     description: 以实物为载体的虚拟礼物，为礼物增添色彩
#     url: #
# Albums
albums: 
  - title: The Flower Of Death
    show-title: false
    image: https://static.turboflint.cn/pico/5/1764382115461.png
    publish: 2025 / 01 / 09
    description: 以神秘的"死亡之花"为名，从此开始慢慢揭晓着虚无背后的秘密和真相。作为新陆地的首张EP专辑，包含了三首单曲以及Rebeeca特别献唱，每一首无不让人感受到无尽的平静。
    url: https://music.163.com/#/album?id=259069654

# Short Videos
short-videos: 
  - title: 第七分钟
    show-title: false
    image: https://static.turboflint.cn/image/diqifenzhong_xiaoshuo.png_compress
    description: 火石首部短片作品，一个既温暖，又短暂的爱情故事。
    type: preview
    publish: false
    projecturl: false
    url: https://www.bilibili.com/video/BV1m98pzzEmt/
    
# Team Members
team-members: 
  - name: 李野树
    avatar: https://static.turboflint.cn/image/ericlee.jpeg
    description: 内容创作者
# Footer
footer: 
  brand:
    name: 涡轮火石
    slogan: 无论是哪个宇宙，都拥有着超越无限的机遇和可能。
    logo: image/logos/logo.png
  links:
    - title: 无界宇宙项目
      url: https://noline.turboflint.cn
    - title: Find Me 找到我文游
      url: https://find-me.turboflint.cn
    - title: 厚浪云
      url: https://hlyun.org
  document:
    - title: Hexo主题文档
      url: https://hexo-theme-docs.turboflint.cn/
  contact:
   - title: GitHub
     url: https://github.com/ericlee517
   - title: Email
     url: mailto:ericlee517@outlook.com
   - title: 微信公众号
     url: ../wechat
  copyright: 李野树
  bottom-slogan: 无论是哪个宇宙，都拥有着超越无限的机遇和可能。